# Generated by Django 5.1.4 on 2025-02-21 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='joined_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='role',
            field=models.CharField(default='owner', max_length=50),
        ),
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
