# Generated by Django 5.1.4 on 2025-01-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableorder',
            options={'verbose_name': 'Table Order', 'verbose_name_plural': 'Table Orders'},
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='item_customizations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='item_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_orders', to='billapp.table'),
        ),
    ]
