# Generated by Django 5.1.4 on 2025-01-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='first_order_time',
        ),
        migrations.RemoveField(
            model_name='tableorder',
            name='last_order_time',
        ),
        migrations.RemoveField(
            model_name='tableorder',
            name='order_date',
        ),
    ]
