# Generated by Django 5.1.4 on 2025-01-26 04:57

import billapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(default=billapp.models.generate_unique_aadhar, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='item_customizations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='item_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='order_id',
            field=models.CharField(default=billapp.models.generate_order_id, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='order_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='payment_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='orders',
            field=models.ManyToManyField(related_name='table_orders', to='billapp.order'),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='KoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_details', models.JSONField(default=dict)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('table_number', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='billapp.orderitem')),
            ],
        ),
    ]
