# Generated by Django 5.1.4 on 2025-01-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_orderitem_rename_total_amount_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_details',
            field=models.JSONField(default=dict),
        ),
    ]
