# Generated by Django 5.1.4 on 2025-02-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_remove_tableorder_first_order_time_and_more'),
    ]

    operations = [
    ]
