# Generated by Django 5.1.4 on 2025-01-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_alter_tableorder_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableOrder',
        ),
    ]
