# Generated by Django 5.1.4 on 2025-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_remove_tableorder_first_order_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='saved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
