# Generated by Django 5.1.4 on 2025-02-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_owner_address_owner_joined_date_owner_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel Profile', 'verbose_name_plural': 'Hotel Profile'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
