# Generated by Django 5.1.4 on 2025-01-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_orderitem_base_price_orderitem_customization_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.JSONField(default=dict),
        ),
    ]
