# Generated by Django 5.1.4 on 2024-12-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr_codes/'),
        ),
    ]
