# Generated by Django 5.1.4 on 2025-01-25 04:05

import billapp.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def fix_duplicate_mobile_numbers(apps, schema_editor):
    Employee = apps.get_model('billapp', 'Employee')
    duplicates = (
        Employee.objects.values('mobile_number')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        mobile_number = duplicate['mobile_number']
        employees = Employee.objects.filter(mobile_number=mobile_number)
        for i, employee in enumerate(employees):
            if i == 0:
                continue  # Keep the first record unchanged
            employee.mobile_number = f"{mobile_number}_{i}"  # Make it unique
            employee.save()


def populate_unique_aadhar(apps, schema_editor):
    Employee = apps.get_model('billapp', 'Employee')
    for employee in Employee.objects.all():
        while True:
            aadhar = billapp.models.generate_unique_aadhar()
            if not Employee.objects.filter(aadhar=aadhar).exists():
                employee.aadhar = aadhar
                employee.save()
                break


def assign_unique_user_ids(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Employee = apps.get_model('billapp', 'Employee')

    existing_users = list(User.objects.all())
    for index, employee in enumerate(Employee.objects.all()):
        if index < len(existing_users):
            employee.user_id = existing_users[index].id  # Assign a unique user_id
        else:
            employee.user_id = None  # Leave blank if no more users are available
        employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_koorder_table_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add new fields
        migrations.AddField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(default=billapp.models.generate_unique_aadhar, max_length=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # Fix duplicate mobile numbers before applying constraints
        migrations.RunPython(
            code=fix_duplicate_mobile_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
        # Populate unique values for user_id
        migrations.RunPython(
            code=assign_unique_user_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Populate unique values for aadhar
        migrations.RunPython(
            code=populate_unique_aadhar,
            reverse_code=migrations.RunPython.noop,
        ),
        # Add unique constraints
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
