# Generated by Django 5.1.4 on 2025-01-25 05:21

import billapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_koorder_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(default=billapp.models.generate_unique_aadhar, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='koorder',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
