# Generated by Django 5.1.4 on 2025-01-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_employee_aadhar_employee_address_and_more'),
    ]

    operations = [
    ]
