# Generated by Django 5.1.4 on 2024-12-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_order_upi_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='upi_qr_code',
        ),
    ]
