# Generated by Django 5.1.4 on 2025-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_targetsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='tableorder',
            name='saved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
