# Generated by Django 5.1.4 on 2025-02-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_connecteddevice_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
