# Generated by Django 5.1.4 on 2025-01-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_order_deleted_by_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_by',
        ),
    ]
