# Generated by Django 5.1.4 on 2025-01-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_item_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('orders', models.ManyToManyField(blank=True, to='billapp.order')),
            ],
        ),
    ]
