# Generated by Django 5.1.4 on 2025-01-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_remove_user_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
            preserve_default=False,
        ),
    ]
