# Generated by Django 5.1.4 on 2025-01-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_add_password_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
