# Generated by Django 5.1.4 on 2025-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_employee_order_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
