# Generated by Django 5.1.4 on 2025-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_item_cost_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='making_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
