# Generated by Django 5.1.4 on 2025-01-25 11:28

import billapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_add_password_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='order_id',
            field=models.CharField(default=billapp.models.generate_order_id, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='order_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='payment_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='table_orders', to='billapp.order'),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
