# Generated by Django 5.1.4 on 2025-01-03 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(blank=True, to='billapp.order')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_order', to='billapp.table')),
            ],
        ),
    ]
