# Generated by Django 5.1.4 on 2025-03-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_orderitem_making_cost'),
    ]

    operations = [
    ]
