# Generated by Django 5.1.4 on 2025-01-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_order_is_temporary_tableorder_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='orders',
        ),
    ]
