# Generated by Django 5.1.4 on 2025-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_remove_tableorder_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='item_customizations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='item_names',
            field=models.JSONField(default=list),
        ),
    ]
