# Generated by Django 5.1.4 on 2025-03-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_auto_20250312_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('table_number', models.CharField(max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='koorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='koorder',
            name='time',
        ),
        migrations.RemoveField(
            model_name='koorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='role',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='status',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='default123', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='koorder',
            name='items',
            field=models.ManyToManyField(related_name='ko_orders', to='billapp.orderitem'),
        ),
        migrations.AlterField(
            model_name='koorder',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_photos/'),
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to='billapp.feedback')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='billapp.item')),
            ],
            options={
                'unique_together': {('feedback', 'item')},
            },
        ),
    ]
