# Generated by Django 5.1.4 on 2025-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_tableorder_item_customizations_tableorder_item_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='orders',
            field=models.ManyToManyField(related_name='table_orders', to='billapp.order'),
        ),
    ]
