# Generated by Django 5.1.7 on 2025-04-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_feedback_remove_koorder_date_remove_koorder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(default='owner001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='owners/'),
        ),
    ]
