# Generated by Django 5.1.4 on 2025-01-27 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_tableorder_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.table'),
        ),
    ]
