# Generated by Django 5.1.4 on 2025-01-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0011_alter_tableorder_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_temporary',
        ),
    ]
