# Generated by Django 5.1.4 on 2025-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0012_remove_order_is_temporary'),
    ]

    operations = [
         migrations.AddField(
            model_name='tableorder',
            name='order_id',
            field=models.CharField(max_length=100, unique=True, default=''),
            preserve_default=False,
         ),
    ]
