# Generated by Django 5.1.4 on 2025-01-27 10:19

import billapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_auto_20250127_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableorder',
            name='order_id',
            field=models.CharField(default=billapp.models.generate_order_id, max_length=100, unique=True),
        ),
    ]
