from django.urls import path, include
from . import views  # Updated import
from .views import table_view, store_order, save_table_order, get_table_order_details  # Import necessary views

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.settings, name='settings'),
    path('inventory/', views.inventory, name='inventory'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('customize/', views.customize, name='customize'),
    path('Privacy_Policy/', views.Privacy_Policy, name='Privacy_Policy'),
    path('menu/', views.menu, name='menu'),
    path('Refund/', views.Refund, name='Refund'),
    path('Terms_Conditions/', views.Terms_Conditions, name='Terms_Conditions'),
    path('tabel/', views.table_view, name='tabel'),
    path('tables/', views.table_view, name='tables'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('save-order/', views.save_order, name='save_order'),
    path('release-table/', views.release_table, name='release_table'),
    path('table-status/', views.get_table_status, name='table_status'),  # Ensure this exists
    path('order-data/', views.order_data, name='order_data'),
    path('order-details/<int:pk>/', views.order_details, name='order_details'),
    path('order-details/<str:order_id>/', views.order_details, name='order_details'),
    path('delete-order/<str:order_id>/', views.delete_order, name='delete_order'),
    path('verify-password/', views.verify_password, name='verify_password'),
    path('send-order/', views.send_order, name='send_order'),
    path('store-order/', store_order, name='store_order'),
    path('ko/', views.ko_view, name='ko'),
    path('fetch-order-data/', views.fetch_order_data, name='fetch_order_data'),
    path('get-order-details/', views.get_order_details, name='get_order_details'),
    path('table-order/<int:table_number>/', views.table_order_view, name='table_order'),
    path('table-order/create/', views.create_table_order, name='create_table_order'),
    path('table-order/<str:table_order_id>/update/', views.update_table_order, name='update_table_order'),
    path('table-order/<str:table_order_id>/delete/', views.delete_table_order, name='delete_table_order'),
    path('save-table-order/', save_table_order, name='save_table_order'),
    path('api/table-order/<int:table_id>/', get_table_order_details, name='get_table_order_details'),
    path('api/check-order-status/<str:table_order_id>/', views.check_order_status, name='check_order_status'),
    path('clear-all-orders/', views.clear_all_orders, name='clear_all_orders'),
    path('complete-order/', views.complete_order, name='complete_order'),
    path('release-table-order/', views.release_table_order, name='release_table_order'),
    path('manage-items/', views.manage_items, name='manage_items'),
    path('manage-items/update/', views.update_item, name='update_item'),
    path('manage-items/delete/<str:form_type>/<int:item_id>/', views.delete_item, name='delete_item'),
    path('manage-items/get-customization/<int:customization_id>/', views.get_customization, name='get-customization'),
    path('manage-items/get/<int:item_id>/', views.get_item_details, name='get_item_details'),
]

urlpatterns += [
    path('reports/', include([
        path('sales/', views.sales_dashboard, name='sales_dashboard'),
        path('items/', views.item_analytics, name='item_analytics'),
        path('customers/', views.customer_insights, name='customer_insights'),
        path('financial/', views.financial_reports, name='financial_reports'),
        path('financial/filter/', views.financial_reports, name='financial_reports_filter'),
    ])),
    path('reports/financial/export/', views.export_financial_report, name='export_financial_report'),
    path('reports/financial/pdf/', views.generate_pdf_report, name='generate_pdf_report'),
    path('reports/financial/share/', views.share_report, name='share_report'),
    path('feedback/', views.feedback, name='feedback'),
    path('submit-feedback/', views.submit_feedback, name='submit_feedback'),
]